# -*- coding: utf-8 -*-
"""housing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ILAD_eophNsXgsx81J1Uf-NBY82HAgps
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import cufflinks as cf
import plotly.io as pio
from sklearn import metrics

USAhousing = pd.read_csv('/content/USA_Housing.csv')
USAhousing.head()

USAhousing.info()

sns.pairplot(USAhousing)

sns.set_style("whitegrid")
sns.distplot(USAhousing['Price'], kde=False, rug=True)

plt.figure(figsize=(18,5))
sns.heatmap(USAhousing.corr(), annot=True, lw=1, linecolor="r", cmap="coolwarm")

X = USAhousing[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms', 'Avg. Area Number of Bedrooms', 'Area Population']]
y = USAhousing['Price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

print(X_train)

print(y_train)

print(X_test)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

predictions = lm.predict(X_test)
print(predictions)

plt.scatter(y_test,predictions)

import cufflinks as cf
cf.go_offline()
import plotly.io as pio
pio.renderers.default = "colab"
pd.DataFrame({"Giá dự đoán":predictions, "Giá ban đầu": y_test}).iplot(mode="markers")

sns.distplot(y_test - predictions)

from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

metrics.explained_variance_score(y_test, predictions)

print(lm.coef_)

coeff_df = pd.DataFrame(lm.coef_, X.columns, columns=['Coefficient'])
coeff_df