# -*- coding: utf-8 -*-
"""tilelaixuat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0kITh7h3erbHUq0O2qFlcOVmhzFnKGY
"""

import pandas as pd
df = pd.read_csv('/content/sample_data/titanic.csv')
df.head(20)
df.isnull().sum()

import numpy as np
df['cabin_null'] = np. where(df['Cabin'].isnull(),1,0)
df['cabin_null'].mean()
df.groupby(['Survived'])['cabin_null'].mean()

df=pd.read_csv('/content/sample_data/titanic.csv',usecols=['Age','Fare','Survived'])
df.isnull().mean()

median=df['Age'].median()
df['Age_median']=df['Age'].fillna(median)
print(df['Age'].std())
print(df['Age_median'].std())

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
df['Age'].plot(kind='kde',color='blue')
df['Age_median'].plot(kind='kde', color='red')
lines, labels = ax.get_legend_handles_labels()
ax.legend(lines, labels, loc='best')

import traitlets

from bs4 import BeautifulSoup
import urllib.request

url = 'https://vnexpress.net'
page = urllib.request.urlopen(url)
soup = BeautifulSoup(page, 'html.parser')
new_feeds=soup.findAll(class_='title_news')

for nfeed in new_feeds:
  feed=nfeed.find("a")
  title=feed.get('title')
  link=feed.get('href')
  if title==None or title=="" or link==None:
    continue
  print('Title: {} - Link: {}'.format(title,link))

